### ISSUE TITLE
Initialize implementations for proxy contracts and protect initialization methods

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-ecdsa#297]
It should be avoided that the implementation of proxy contracts can be initialized by third parties. This can be the case if the `initialize` function is unprotected. Since the implementation contract is not meant to be used directly without a proxy delegate-calling it is recommended to protect the initialization method of the implementation by initializing on deployment.

When working on this issue, please take care of `BondedECDSAKeepVendorImplV1` initialization but also make sure there are no other similar problems in other places of the code.

**Comment by nkuba** [comment]
@tintinweb's suggestions are handled in https://github.com/keep-network/keep-ecdsa/pull/323.
