### ISSUE TITLE
Fee refund when key generation fails

### ISSUE THREAD

**Issue by nkuba** [keep-network/keep-ecdsa#324]
The owner of the keep should be able to get a fee refund in case the public key generation fails within a specific timeout.
Right now the keep owner can seize all the bonds even though the public key has not been generated yet. Full signer bonds seizure should be possible in a limited number of cases, e.g. frauds.

Should the members get punished (slashed)?

This issue requires further clarification before implementation. 

Refs: https://github.com/keep-network/tbtc/issues/495

**Comment by pdyraga** [comment]
Done in https://github.com/keep-network/tbtc/pull/520, confirmed with @Shadowfiend there is nothing on keep side that has to be done here. It's solved by seizing signer bonds.
