### ISSUE TITLE
Wait for enough confirmations before signing.

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-ecdsa#364]
We need to track adding a delay to wait for a few confirmations to build up on top of the request. If it gets reorged away, we'll end up with ECDSA fraud exposure. Additionally, we should track which events have been handled so that we don't handle the same event more than one time in case it gets delivered more than once (observed on Infura couple of times); see #355

**Comment by Shadowfiend** [comment]
To do this right we'll want to make sure that after the given time has elapsed, the transaction still exists on the current chain.

**Comment by pdyraga** [comment]
Yep, our plan is to receive the event, wait for N blocks, and then check again. We'll also need to register this event somewhere so that we don't handle more than once (#355)

**Comment by nkuba** [comment]
Thoughts around the reasonable block confirmation number?

**Comment by pdyraga** [comment]
I'd say `5` to be sure but this affects tBTC signing times. Maybe we need another step in the redemption flow?

**Comment by Shadowfiend** [comment]
6-12 feels right… Signing window for tBTC is in hours, right? The 3-4 minutes delay here shouldn't have a huge impact?

**Comment by pdyraga** [comment]
It may have an impact on user experience in dApp, that's the only one piece I am worried about.

**Comment by Shadowfiend** [comment]
Ah. Let's focus on security here, and figure out how to handle this in the dApp separately I think. The right solution from a dApp perspective is probably that the signers submit the Bitcoin tx anyway, tbh.
