### ISSUE TITLE
Compilation breaks if `abigen` is too new

### ISSUE THREAD

**Issue by liamzebedee** [keep-network/keep-ecdsa#439]
We currently use `abigen` to generate contract bindings for the keep-ecdsa contracts. 

I recently ran into an issue where a Homebrew-installed `abigen` binary was used (from the `ethereum` brew formulae), which was generating bindings for a later version of the `ethereum` package we use. The method `RawTransact` was recently introduced in `github.com/ethereum/go-ethereum v1.9.13`, however we depend on `v1.9.10`. This produces errors while running `go generate ./...`:

```
pkg/chain/gen/abi/BondedECDSAKeepFactory.go:820:2: not enough arguments to return
pkg/chain/gen/abi/BondedECDSAKeepFactory.go:820:41: _BondedECDSAKeepFactory.contract.RawTransact undefined (type *bind.BoundContract has no field or method RawTransact)
pkg/chain/gen/abi/BondedECDSAKeepVendor.go:377:2: not enough arguments to return
pkg/chain/gen/abi/BondedECDSAKeepVendor.go:377:40: _BondedECDSAKeepVendor.contract.RawTransact undefined (type *bind.BoundContract has no field or method RawTransact)
```

Perhaps we can either:

 1. Modify makefile to use `$GOPATH/bin/abigen`, avoiding any conflicts
 2. Warn/error if `abigen -v` matches a different version

[Flowdock thread context](https://www.flowdock.com/app/cardforcoin/tech/threads/Espz5foiPIYvFWlA0oKCp8vFP0e)

**Comment by Shadowfiend** [comment]
`GOPATH` won't work as it's optional these days, but we can resolve it similar to how we resolve our own code generators, I think.

**Comment by Shadowfiend** [comment]
Sounds like @ironng ran into this as well. Here and in keep-core, changing invocations of `abigen` in [the Makefiles](https://github.com/keep-network/keep-ecdsa/blob/050cc064dd679ce0494521df3785581aaed090d5/pkg/chain/gen/Makefile#L45) to, roughly, `go run github.com/ethereum/go-ethereum/cmd/abigen` instead. That should run the package-specific version of `abigen`, I believe, as it does with the keep-common generators.

**Comment by ElderOrb** [comment]
I've confronted it too, any ETA on fix?

**Comment by ElderOrb** [comment]
Interesting, proposed by @Shadowfiend solution does work on clean environment. Seems like I've corrupted my previous environment by crazy senseless experiments :).
