### ISSUE TITLE
"received message we didn't subscribe to. Dropping." logged

### ISSUE THREAD

**Issue by nkuba** [keep-network/keep-ecdsa#455]
On production, we get a lot of `received message we didn't subscribe to. Dropping.` logged.
Happened on ecdsa bootstrap node.

**Comment by Shadowfiend** [comment]
Worth noting, this is also happening on some beacon clients.

**Comment by pdyraga** [comment]
Fixed in https://github.com/keep-network/keep-core/pull/1807 and https://github.com/keep-network/keep-ecdsa/pull/456
