### ISSUE TITLE
Configurable size of safe prime pool

### ISSUE THREAD

**Issue by liamzebedee** [keep-network/keep-ecdsa#474]
https://github.com/keep-network/keep-ecdsa/blob/a9479a2df1713d693dd0995ebf154b34ea0fbe0e/pkg/node/params_pool.go#L24

Running a local ECDSA network of 3 nodes, generating such a poolSize of 20 params on startup slows down my rather well-equipped Macbook to a halt for ~10-15 minutes. 

Is it possible to improve the dev UX here? I've configured the poolSize to `1` locally, and am finding the lazy generation of parameters for deposits is more than satisfactory (~10s). I'm thinking of potential tBTC dapp developers, that might not have such beefy machines, and are running something like [local-setup](https://github.com/keep-network/local-setup).

**Comment by Shadowfiend** [comment]
Hmmm... Probably not crazy to make this overrideable in config or via command line flag... Probably config if it’s likely to be environmental rather than execution based.

**Comment by liamzebedee** [comment]
When would execution-based be suitable @Shadowfiend? Out of curiosity.

**Comment by mhluongo** [comment]
> When would execution-based be suitable

I'm not @Shadowfiend, but typically you want to separate config for difference "instances" of a running application from normal concerns that would come up in a single instance.

**Comment by nkuba** [comment]
The pool size should be overridable in the config file, as this would be consistent with how we handle other runtime parameters.
 https://github.com/keep-network/keep-ecdsa/blob/941216416079c24ab414c9da32ce955aa8dba01d/configs/config.toml.SAMPLE#L77-L82

Having this would be beneficial not only for development environments but also for production where e.g. bootstrap nodes.
