### ISSUE TITLE
Allow the application to configure expectations about the minimum bond

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-ecdsa#506]
Right now, bonded sortition pool updates the minimum bondable value for each successful signer set selection. This way, the gas cost of skipping ineligible signers can be minimized and the sortition pool automatically adjusts the requirements based on the current application's expectations.

Instead of doing it automatically, we could have the application set the minimum bondable value and leave the responsibility of keeping this value sane, balancing signer selection cost, to the application. For tBTC, this value could be the minimum lot size.

**Comment by pdyraga** [comment]
@eth-r I am very interested in your thoughts here.

**Comment by eth-r** [comment]
This is reasonable. With sortition pools being fairly optimized wrt querying costs, we should be fine even if we need to skip a lot of low-bond operators for larger lot sizes.
