### ISSUE TITLE
ECDSA client is a little too aggressive about submitting the transaction signature.

### ISSUE THREAD

**Issue by suprnrdy** [keep-network/keep-ecdsa#553]
During tBTC redemption, the ECDSA Clients submit the transaction signature too soon, leading to failed transactions from the operators `Fail with error 'Not awaiting a signature`.  Two options is to reduce the time between submissions, or have each operator try in the order they are in from membership list. 

<img width="963" alt="Screen Shot 2020-09-22 at 10 17 28 AM" src="https://user-images.githubusercontent.com/1414501/93915963-a7a75000-fcbd-11ea-89b2-65d14a14d13d.png">

<img width="727" alt="Screen Shot 2020-09-22 at 10 24 06 AM" src="https://user-images.githubusercontent.com/1414501/93916250-1684a900-fcbe-11ea-96ea-058236cfc89d.png">

<img width="752" alt="Screen Shot 2020-09-22 at 10 35 11 AM" src="https://user-images.githubusercontent.com/1414501/93917097-5ef09680-fcbf-11ea-9472-3fb801a322fb.png">

**Comment by pdyraga** [comment]
Thanks for reporting this @suprnrdy, this is true and we'll be working on improving gas cost efficiency.
