### ISSUE TITLE
WARNING: proto: message SignRound8Message is already registered

### ISSUE THREAD

**Issue by Toltekayotl** [keep-network/keep-ecdsa#565]
Debian 4.19.146-1 

Run docker container:
sudo docker run -d \
  --restart always \
  --entrypoint /usr/local/bin/keep-ecdsa \
  --volume $HOME/keep-ecdsa:/mnt/keep-ecdsa \
  --env KEEP_ETHEREUM_PASSWORD=..... \
  --env LOG_LEVEL=debug \
  --name ecdsa \
  -p 3920:3920 \
  keepnetwork/keep-ecdsa-client:v1.2.0-rc.5 \ --config /mnt/keep-ecdsa/config/config.toml start

Logs:
2020/09/29 17:15:36 WARNING: proto: message SignRound1Message2 is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2020/09/29 17:15:36 WARNING: proto: message SignRound2Message is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2020/09/29 17:15:36 WARNING: proto: message SignRound3Message is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2020/09/29 17:15:36 WARNING: proto: message SignRound4Message is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2020/09/29 17:15:36 WARNING: proto: message SignRound5Message is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2020/09/29 17:15:36 WARNING: proto: message SignRound6Message is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2020/09/29 17:15:36 WARNING: proto: message SignRound7Message is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2020/09/29 17:15:36 WARNING: proto: message SignRound8Message is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2020/09/29 17:15:36 WARNING: proto: message SignRound9Message is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

No help topic for ' --config'

**Comment by kferretcrypto** [comment]
@Toltekayotl If you're having an issue starting your server, it's because you have an extra `\` character before your `--config`. Just remove that and it should work. That's meant for multiline commands so you don't need it there.

The warning is just a warning I believe and does not interfere with operation. @lukasz-zimnoch already opened an issue for this in the library that's causing it: https://github.com/binance-chain/tss-lib/issues/106

**Comment by pdyraga** [comment]
Thanks for reporting it @Toltekayotl. @kferretcrypto is right, please remove extra `\` and you should be good. Those warnings are confusing but we can not do much about them until binance-chain/tss-lib#106 gets done.
