### ISSUE TITLE
Expose metric for tss params pool size

### ISSUE THREAD

**Issue by nkuba** [keep-network/keep-ecdsa#577]
Add current TSS pre parameters pool size to the metrics API.

**Comment by Shadowfiend** [comment]
Just to check, this is for the _current_ pool size, as opposed to the target pool size?

**Comment by pdyraga** [comment]
That's my understanding, the target pool size is not that interesting as the current value.

**Comment by nkuba** [comment]
Correct, it's for the current number of params sitting in the pool.
