### ISSUE TITLE
no minimum KEEP stake or operator is not authorized to use it;

### ISSUE THREAD

**Issue by eyebrown** [keep-network/keep-ecdsa#609]
I excuted  install.sh and initialize.sh successfully. But when I use  start.sh to start keep-ecdsa client ,it displays: 

no minimum KEEP stake or operator is not authorized to use it; please make sure the operator address in the configuration is correct and it has KEEP tokens delegated and the operator contract has been authorized to operate on the stake%

**Comment by mhluongo** [comment]
Hey @eyebrown, sounds like you haven't staked tokens or authorized the ECDSA contracts?

There are folks around to help on Discord if you want live support https://chat.keep.network
