### ISSUE TITLE
Incorrect interval ending block for 2020-12-04 -> 2020-12-11 rewards allocation period.  

### ISSUE THREAD

**Issue by AJolly** [keep-network/keep-ecdsa#646]
11426284 does not appear to be the correct interval ending block for 2020-12-04 -> 2020-12-11 rewards allocation period.  

https://github.com/keep-network/keep-ecdsa/pull/644/commits/9503b9d13bec63fad49b15c8a2fa3a2b0c60351e   

Everything else I've checked validates, but that doc says that block 11426284 ends at 
Interval end timestamp: 2020-12-11T00:00:00.000Z, but that doesn't match when I look it up elsewhere

For example:
11291625   25 days 10 hrs ago (Nov-20-2020 12:00:01 AM +UTC)
11337172   18 days 10 hrs ago (Nov-27-2020 12:00:18 AM +UTC)
11382789   11 days 10 hrs ago (Dec-04-2020 12:00:25 AM +UTC)
11426284    4 days 18 hrs ago (Dec-10-2020 04:33:20 PM +UTC)

**Comment by pdyraga** [comment]
Thanks for reporting it @AJolly. The interval was regenerated in the commit referenced above.

As a quick fix to the scripts, I'd consider making start and end block input parameters and extract `ethereum-block-by-date` lookup into a separate command. This way, we'll get repeatable results and make sure no blocks are omitted or overlapping between intervals even if `ethereum-block-by-date` does not return the most accurate and repeatable results. @lukasz-zimnoch thoughts on that one?

**Comment by lukasz-zimnoch** [comment]
Yeah sounds good!
